/*
**
** The C code is generated by [ATS/Postiats-0-3-11]
** The starting compilation time is: 2018-10-24: 22h: 8m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/string.dats: 1631(line=50, offs=1) -- 1670(line=50, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/array.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/SHARE/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/SHARE/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.3.11/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(setPinHigh_in_c, (atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatmpdec(statmp1, atstype_funptr) ;
ATSstatic()
atsvoid_t0ype
__patsfun_0(atstype_boxed, atstkind_t0ype(atstype_int)) ;

ATSstatic()
atsvoid_t0ype
__patsfun_1(atstype_boxed, atstkind_t0ype(atstype_int)) ;

/*
/home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 369(line=32, offs=26) -- 606(line=37, offs=37)
*/
/*
local: 
global: __patsfun_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
__patsfun_0(atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 369(line=32, offs=26) -- 606(line=37, offs=37)
*/
ATSINSflab(__patsflab___patsfun_0):
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 403(line=32, offs=60) -- 606(line=37, offs=37)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 420(line=33, offs=5) -- 428(line=33, offs=13)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 373(line=32, offs=30) -- 377(line=32, offs=34)
*/
ATSifnthen(ATSCKpat_con0(arg0, 0)) { ATSINSgoto(__atstmplab2) ; } ;
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 428(line=33, offs=13) -- 428(line=33, offs=13)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 432(line=33, offs=17) -- 452(line=33, offs=37)
*/
ATSINSmove_void(tmpret0, setPinHigh_in_c(ATSPMVi0nt(0), arg1)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 460(line=34, offs=5) -- 468(line=34, offs=13)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 373(line=32, offs=30) -- 377(line=32, offs=34)
*/
ATSifnthen(ATSCKpat_con0(arg0, 1)) { ATSINSgoto(__atstmplab4) ; } ;
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 468(line=34, offs=13) -- 468(line=34, offs=13)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 472(line=34, offs=17) -- 492(line=34, offs=37)
*/
ATSINSmove_void(tmpret0, setPinHigh_in_c(ATSPMVi0nt(1), arg1)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 498(line=35, offs=5) -- 506(line=35, offs=13)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 373(line=32, offs=30) -- 377(line=32, offs=34)
*/
ATSifnthen(ATSCKpat_con0(arg0, 2)) { ATSINSgoto(__atstmplab6) ; } ;
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 506(line=35, offs=13) -- 506(line=35, offs=13)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 510(line=35, offs=17) -- 530(line=35, offs=37)
*/
ATSINSmove_void(tmpret0, setPinHigh_in_c(ATSPMVi0nt(2), arg1)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 536(line=36, offs=5) -- 544(line=36, offs=13)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 373(line=32, offs=30) -- 377(line=32, offs=34)
*/
ATSifnthen(ATSCKpat_con0(arg0, 3)) { ATSINSgoto(__atstmplab8) ; } ;
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 544(line=36, offs=13) -- 544(line=36, offs=13)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 548(line=36, offs=17) -- 568(line=36, offs=37)
*/
ATSINSmove_void(tmpret0, setPinHigh_in_c(ATSPMVi0nt(3), arg1)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 574(line=37, offs=5) -- 582(line=37, offs=13)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 373(line=32, offs=30) -- 377(line=32, offs=34)
*/
ATSifnthen(ATSCKpat_con0(arg0, 4)) { ATSINScaseof_fail("/home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 403(line=32, offs=60) -- 606(line=37, offs=37)") ; } ;
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 582(line=37, offs=13) -- 582(line=37, offs=13)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 586(line=37, offs=17) -- 606(line=37, offs=37)
*/
ATSINSmove_void(tmpret0, setPinHigh_in_c(ATSPMVi0nt(4), arg1)) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [__patsfun_0] */

/*
/home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 633(line=41, offs=18) -- 694(line=41, offs=79)
*/
/*
local: 
global: __patsfun_1$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
__patsfun_1(atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret2) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 633(line=41, offs=18) -- 694(line=41, offs=79)
*/
ATSINSflab(__patsflab___patsfun_1):
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 666(line=41, offs=51) -- 694(line=41, offs=79)
*/
ATSINSmove_void(tmpret2, ATSfunclo_fun(statmp1, (atstype_boxed, atstkind_t0ype(atstype_int)), atsvoid_t0ype)(arg0, arg1)) ;

ATSfunbody_end()
ATSreturn_void(tmpret2) ;
} /* end of [__patsfun_1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_scott_057_programs_057_ats_057_arduino_055_makefile_055_ats_057_examples_057_BlinkInCircuitPlayground_057_DATS_057_circuit_playground_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_scott_057_programs_057_ats_057_arduino_055_makefile_055_ats_057_examples_057_BlinkInCircuitPlayground_057_DATS_057_circuit_playground_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_scott_057_programs_057_ats_057_arduino_055_makefile_055_ats_057_examples_057_BlinkInCircuitPlayground_057_DATS_057_circuit_playground_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_scott_057_programs_057_ats_057_arduino_055_makefile_055_ats_057_examples_057_BlinkInCircuitPlayground_057_DATS_057_circuit_playground_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/*
emit_instr: loc0 = /home/scott/programs/ats/arduino-makefile-ats/examples/BlinkInCircuitPlayground/DATS/circuit_playground.dats: 348(line=32, offs=5) -- 366(line=32, offs=23)
*/
ATSINSmove(statmp1, ATSPMVfunlab(__patsfun_0)) ;
/* in of [local] */
/* (*nothing*) */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
